// <auto-generated />
using System;
using System.Collections.Generic;
using System.Text.Json;
using AIKnowledge.Storage.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;
using Pgvector;

#nullable disable

namespace AIKnowledge.Storage.Migrations
{
    [DbContext(typeof(KnowledgeDbContext))]
    [Migration("20260207041400_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AIKnowledge.Storage.Data.Entities.BatchDocumentEntity", b =>
                {
                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.HasKey("BatchId", "DocumentId");

                    b.HasIndex("DocumentId");

                    b.ToTable("batch_documents", (string)null);
                });

            modelBuilder.Entity("AIKnowledge.Storage.Data.Entities.BatchEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("Completed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("completed");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Failed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("failed");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Processing")
                        .HasColumnName("status");

                    b.Property<int>("TotalFiles")
                        .HasColumnType("integer")
                        .HasColumnName("total_files");

                    b.HasKey("Id");

                    b.ToTable("batches", (string)null);
                });

            modelBuilder.Entity("AIKnowledge.Storage.Data.Entities.ChunkEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("integer")
                        .HasColumnName("chunk_index");

                    b.Property<Guid>("ContainerId")
                        .HasColumnType("uuid")
                        .HasColumnName("container_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<int>("EndOffset")
                        .HasColumnType("integer")
                        .HasColumnName("end_offset");

                    b.Property<Dictionary<string, string>>("Metadata")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search_vector")
                        .HasComputedColumnSql("to_tsvector('english', content)", true);

                    b.Property<int>("StartOffset")
                        .HasColumnType("integer")
                        .HasColumnName("start_offset");

                    b.Property<int>("TokenCount")
                        .HasColumnType("integer")
                        .HasColumnName("token_count");

                    b.HasKey("Id");

                    b.HasIndex("ContainerId")
                        .HasDatabaseName("idx_chunks_container_id");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("idx_chunks_document_id");

                    b.HasIndex("SearchVector")
                        .HasDatabaseName("idx_chunks_fts");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "GIN");

                    b.ToTable("chunks", (string)null);
                });

            modelBuilder.Entity("AIKnowledge.Storage.Data.Entities.ChunkVectorEntity", b =>
                {
                    b.Property<Guid>("ChunkId")
                        .HasColumnType("uuid")
                        .HasColumnName("chunk_id");

                    b.Property<Guid>("ContainerId")
                        .HasColumnType("uuid")
                        .HasColumnName("container_id");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(768)")
                        .HasColumnName("embedding");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model_id");

                    b.HasKey("ChunkId");

                    b.HasIndex("ContainerId")
                        .HasDatabaseName("idx_chunk_vectors_container_id");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("idx_chunk_vectors_document_id");

                    b.HasIndex("Embedding")
                        .HasDatabaseName("idx_chunk_vectors_embedding")
                        .HasAnnotation("Npgsql:StorageParameter:lists", 100);

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "ivfflat");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_cosine_ops" });

                    b.ToTable("chunk_vectors", (string)null);
                });

            modelBuilder.Entity("AIKnowledge.Storage.Data.Entities.ContainerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_containers_name");

                    b.ToTable("containers", (string)null);
                });

            modelBuilder.Entity("AIKnowledge.Storage.Data.Entities.DocumentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("ChunkCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("chunk_count");

                    b.Property<Guid>("ContainerId")
                        .HasColumnType("uuid")
                        .HasColumnName("container_id");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_hash");

                    b.Property<string>("ContentType")
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<DateTime?>("LastIndexedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_indexed_at");

                    b.Property<Dictionary<string, string>>("Metadata")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("path");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ContainerId")
                        .HasDatabaseName("idx_documents_container_id");

                    b.HasIndex("ContainerId", "Path")
                        .IsUnique()
                        .HasDatabaseName("idx_documents_container_path");

                    b.ToTable("documents", (string)null);
                });

            modelBuilder.Entity("AIKnowledge.Storage.Data.Entities.FolderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ContainerId")
                        .HasColumnType("uuid")
                        .HasColumnName("container_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("path");

                    b.HasKey("Id");

                    b.HasIndex("ContainerId", "Path")
                        .IsUnique()
                        .HasDatabaseName("ix_folders_container_path");

                    b.ToTable("folders", (string)null);
                });

            modelBuilder.Entity("AIKnowledge.Storage.Data.Entities.SettingEntity", b =>
                {
                    b.Property<string>("Category")
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<JsonDocument>("Values")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("values")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.HasKey("Category");

                    b.ToTable("settings", (string)null);
                });

            modelBuilder.Entity("AIKnowledge.Storage.Data.Entities.BatchDocumentEntity", b =>
                {
                    b.HasOne("AIKnowledge.Storage.Data.Entities.BatchEntity", "Batch")
                        .WithMany("BatchDocuments")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AIKnowledge.Storage.Data.Entities.DocumentEntity", "Document")
                        .WithMany("BatchDocuments")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("AIKnowledge.Storage.Data.Entities.ChunkEntity", b =>
                {
                    b.HasOne("AIKnowledge.Storage.Data.Entities.DocumentEntity", "Document")
                        .WithMany("Chunks")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("AIKnowledge.Storage.Data.Entities.ChunkVectorEntity", b =>
                {
                    b.HasOne("AIKnowledge.Storage.Data.Entities.ChunkEntity", "Chunk")
                        .WithOne("ChunkVector")
                        .HasForeignKey("AIKnowledge.Storage.Data.Entities.ChunkVectorEntity", "ChunkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AIKnowledge.Storage.Data.Entities.DocumentEntity", "Document")
                        .WithMany("ChunkVectors")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chunk");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("AIKnowledge.Storage.Data.Entities.DocumentEntity", b =>
                {
                    b.HasOne("AIKnowledge.Storage.Data.Entities.ContainerEntity", "Container")
                        .WithMany("Documents")
                        .HasForeignKey("ContainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Container");
                });

            modelBuilder.Entity("AIKnowledge.Storage.Data.Entities.FolderEntity", b =>
                {
                    b.HasOne("AIKnowledge.Storage.Data.Entities.ContainerEntity", "Container")
                        .WithMany("Folders")
                        .HasForeignKey("ContainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Container");
                });

            modelBuilder.Entity("AIKnowledge.Storage.Data.Entities.BatchEntity", b =>
                {
                    b.Navigation("BatchDocuments");
                });

            modelBuilder.Entity("AIKnowledge.Storage.Data.Entities.ChunkEntity", b =>
                {
                    b.Navigation("ChunkVector");
                });

            modelBuilder.Entity("AIKnowledge.Storage.Data.Entities.ContainerEntity", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Folders");
                });

            modelBuilder.Entity("AIKnowledge.Storage.Data.Entities.DocumentEntity", b =>
                {
                    b.Navigation("BatchDocuments");

                    b.Navigation("ChunkVectors");

                    b.Navigation("Chunks");
                });
#pragma warning restore 612, 618
        }
    }
}
