name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues and discussions to ensure this hasn't been suggested
          required: true
        - label: I have read the [project roadmap](../../README.md#roadmap) and this isn't already planned
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Is your feature request related to a pain point?
      placeholder: Describe the problem or limitation you're experiencing
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work? Describe your ideal solution.
      placeholder: Describe the feature you'd like to see implemented
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: Describe any alternative solutions or features you've considered

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: Which area of the platform does this feature relate to?
      options:
        - Document Ingestion
        - Search & Retrieval
        - Container Management
        - Web UI
        - CLI
        - MCP Server
        - API
        - Settings & Configuration
        - Security & Authentication
        - Performance
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority (Your Perspective)
      description: How important is this feature to you?
      options:
        - Critical - Blocking my use case
        - High - Would significantly improve my workflow
        - Medium - Nice to have
        - Low - Minor enhancement
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe how you would use this feature in practice
      placeholder: |
        Example scenario:
        1. As a [user type]
        2. I want to [action]
        3. So that [benefit]
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Examples or References
      description: Are there similar implementations in other tools? Include links or examples.
      placeholder: Links to similar features in other projects, mockups, screenshots, etc.

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to contribute to this feature?
      options:
        - label: I would be willing to submit a PR for this feature
        - label: I would be willing to help test this feature
        - label: I would be willing to help with documentation

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or information about the feature request
      placeholder: Add any other context about the feature request here
