// <auto-generated />
using System;
using System.Collections.Generic;
using System.Text.Json;
using Connapse.Storage.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;
using Pgvector;

#nullable disable

namespace Connapse.Storage.Migrations
{
    [DbContext(typeof(KnowledgeDbContext))]
    partial class KnowledgeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Connapse.Storage.Data.Entities.BatchDocumentEntity", b =>
                {
                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.HasKey("BatchId", "DocumentId");

                    b.HasIndex("DocumentId");

                    b.ToTable("batch_documents", (string)null);
                });

            modelBuilder.Entity("Connapse.Storage.Data.Entities.BatchEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("Completed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("completed");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Failed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("failed");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Processing")
                        .HasColumnName("status");

                    b.Property<int>("TotalFiles")
                        .HasColumnType("integer")
                        .HasColumnName("total_files");

                    b.HasKey("Id");

                    b.ToTable("batches", (string)null);
                });

            modelBuilder.Entity("Connapse.Storage.Data.Entities.ChunkEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("integer")
                        .HasColumnName("chunk_index");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<int>("EndOffset")
                        .HasColumnType("integer")
                        .HasColumnName("end_offset");

                    b.Property<Dictionary<string, string>>("Metadata")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search_vector")
                        .HasComputedColumnSql("setweight(to_tsvector('simple', coalesce(content, '')), 'A') || setweight(to_tsvector('english', coalesce(content, '')), 'B')", true);

                    b.Property<int>("StartOffset")
                        .HasColumnType("integer")
                        .HasColumnName("start_offset");

                    b.Property<int>("TokenCount")
                        .HasColumnType("integer")
                        .HasColumnName("token_count");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("idx_chunks_document_id");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("idx_chunks_owner_id");

                    b.HasIndex("SearchVector")
                        .HasDatabaseName("idx_chunks_fts");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "GIN");

                    b.ToTable("chunks", (string)null);
                });

            modelBuilder.Entity("Connapse.Storage.Data.Entities.ChunkVectorEntity", b =>
                {
                    b.Property<Guid>("ChunkId")
                        .HasColumnType("uuid")
                        .HasColumnName("chunk_id");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<int?>("Dimensions")
                        .HasColumnType("integer")
                        .HasColumnName("dimensions");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector")
                        .HasColumnName("embedding");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model_id");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.HasKey("ChunkId");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("idx_chunk_vectors_document_id");

                    b.HasIndex("ModelId")
                        .HasDatabaseName("idx_chunk_vectors_model_id");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("idx_chunk_vectors_owner_id");

                    b.HasIndex("ContentHash", "ModelId", "Dimensions")
                        .HasDatabaseName("idx_chunk_vectors_cache_lookup")
                        .HasFilter("\"content_hash\" IS NOT NULL AND \"dimensions\" IS NOT NULL");

                    b.ToTable("chunk_vectors", (string)null);
                });

            modelBuilder.Entity("Connapse.Storage.Data.Entities.ConnectionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<JsonDocument>("ConfigJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("config");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<int>("Provider")
                        .HasColumnType("integer")
                        .HasColumnName("provider");

                    b.Property<string>("SecretProtected")
                        .HasColumnType("text")
                        .HasColumnName("secret_protected");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_connections_name");

                    b.ToTable("connections", (string)null);
                });

            modelBuilder.Entity("Connapse.Storage.Data.Entities.ContainerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<JsonDocument>("SettingsOverridesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("settings_overrides");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<string>("SummaryDocSetHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("summary_doc_set_hash");

                    b.Property<DateTime?>("SummaryGeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("summary_generated_at");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_containers_name");

                    b.ToTable("containers", (string)null);
                });

            modelBuilder.Entity("Connapse.Storage.Data.Entities.DocumentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("ChunkCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("chunk_count");

                    b.Property<Guid?>("ContainerId")
                        .HasColumnType("uuid")
                        .HasColumnName("container_id");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_hash");

                    b.Property<string>("ContentType")
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<int>("Generation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("generation");

                    b.Property<string>("IngestionState")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("ingestion_state");

                    b.Property<DateTime?>("LastIndexedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_indexed_at");

                    b.Property<Dictionary<string, string>>("Metadata")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<Guid>("OwnerId")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id")
                        .HasComputedColumnSql("COALESCE(container_id, source_id)", true);

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("path");

                    b.Property<string>("ResourceUri")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("resource_uri");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<string>("SummaryContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("summary_content_hash");

                    b.Property<DateTime?>("SummaryGeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("summary_generated_at");

                    b.HasKey("Id");

                    b.HasIndex("ContainerId")
                        .HasDatabaseName("idx_documents_container_id");

                    b.HasIndex("IngestionState")
                        .HasDatabaseName("ix_documents_ingestion_state");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_documents_owner_id");

                    b.HasIndex("ResourceUri")
                        .HasDatabaseName("idx_documents_resource_uri");

                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("ResourceUri"), new[] { "text_pattern_ops" });

                    b.HasIndex("SourceId")
                        .HasDatabaseName("idx_documents_source_id");

                    b.HasIndex("OwnerId", "Path")
                        .IsUnique()
                        .HasDatabaseName("idx_documents_owner_path");

                    b.ToTable("documents", null, t =>
                        {
                            t.HasCheckConstraint("ck_documents_single_owner", "(container_id IS NULL) <> (source_id IS NULL)");
                        });
                });

            modelBuilder.Entity("Connapse.Storage.Data.Entities.FolderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ContainerId")
                        .HasColumnType("uuid")
                        .HasColumnName("container_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("path");

                    b.HasKey("Id");

                    b.HasIndex("ContainerId", "Path")
                        .IsUnique()
                        .HasDatabaseName("ix_folders_container_path");

                    b.ToTable("folders", (string)null);
                });

            modelBuilder.Entity("Connapse.Storage.Data.Entities.ProviderCredentialEntity", b =>
                {
                    b.Property<string>("Provider")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("provider");

                    b.Property<string>("CertificatePem")
                        .HasColumnType("text")
                        .HasColumnName("certificate_pem");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("PrincipalName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("principal_name");

                    b.Property<string>("PrivateKeyProtected")
                        .HasColumnType("text")
                        .HasColumnName("private_key_protected");

                    b.Property<string>("ProfileArn")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("profile_arn");

                    b.Property<string>("Region")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("region");

                    b.Property<string>("RoleArn")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("role_arn");

                    b.Property<string>("TrustAnchorArn")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("trust_anchor_arn");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.HasKey("Provider");

                    b.ToTable("provider_credentials", (string)null);
                });

            modelBuilder.Entity("Connapse.Storage.Data.Entities.SettingEntity", b =>
                {
                    b.Property<string>("Category")
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<JsonDocument>("Values")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("values")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.HasKey("Category");

                    b.ToTable("settings", (string)null);
                });

            modelBuilder.Entity("Connapse.Storage.Data.Entities.SourceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConnectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("connection_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("enabled");

                    b.Property<string>("LastSyncError")
                        .HasColumnType("text")
                        .HasColumnName("last_sync_error");

                    b.Property<int>("LastSyncStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("last_sync_status");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<JsonDocument>("ScopeJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("scope");

                    b.Property<JsonDocument>("SettingsOverridesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("settings_overrides");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<string>("SummaryDocSetHash")
                        .HasColumnType("text")
                        .HasColumnName("summary_doc_set_hash");

                    b.Property<DateTime?>("SummaryGeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("summary_generated_at");

                    b.Property<string>("SyncCursor")
                        .HasColumnType("text")
                        .HasColumnName("sync_cursor");

                    b.Property<int?>("SyncIntervalSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("sync_interval_seconds");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("WithheldDeletions")
                        .HasColumnType("integer")
                        .HasColumnName("withheld_deletions");

                    b.HasKey("Id");

                    b.HasIndex("ConnectionId")
                        .HasDatabaseName("ix_sources_connection_id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_sources_name");

                    b.ToTable("sources", (string)null);
                });

            modelBuilder.Entity("Connapse.Storage.Data.Entities.BatchDocumentEntity", b =>
                {
                    b.HasOne("Connapse.Storage.Data.Entities.BatchEntity", "Batch")
                        .WithMany("BatchDocuments")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Connapse.Storage.Data.Entities.DocumentEntity", "Document")
                        .WithMany("BatchDocuments")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("Connapse.Storage.Data.Entities.ChunkEntity", b =>
                {
                    b.HasOne("Connapse.Storage.Data.Entities.DocumentEntity", "Document")
                        .WithMany("Chunks")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("Connapse.Storage.Data.Entities.ChunkVectorEntity", b =>
                {
                    b.HasOne("Connapse.Storage.Data.Entities.ChunkEntity", "Chunk")
                        .WithOne("ChunkVector")
                        .HasForeignKey("Connapse.Storage.Data.Entities.ChunkVectorEntity", "ChunkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Connapse.Storage.Data.Entities.DocumentEntity", "Document")
                        .WithMany("ChunkVectors")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chunk");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("Connapse.Storage.Data.Entities.DocumentEntity", b =>
                {
                    b.HasOne("Connapse.Storage.Data.Entities.ContainerEntity", "Container")
                        .WithMany("Documents")
                        .HasForeignKey("ContainerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Connapse.Storage.Data.Entities.SourceEntity", "Source")
                        .WithMany("Documents")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Container");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("Connapse.Storage.Data.Entities.FolderEntity", b =>
                {
                    b.HasOne("Connapse.Storage.Data.Entities.ContainerEntity", "Container")
                        .WithMany("Folders")
                        .HasForeignKey("ContainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Container");
                });

            modelBuilder.Entity("Connapse.Storage.Data.Entities.SourceEntity", b =>
                {
                    b.HasOne("Connapse.Storage.Data.Entities.ConnectionEntity", "Connection")
                        .WithMany("Sources")
                        .HasForeignKey("ConnectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Connection");
                });

            modelBuilder.Entity("Connapse.Storage.Data.Entities.BatchEntity", b =>
                {
                    b.Navigation("BatchDocuments");
                });

            modelBuilder.Entity("Connapse.Storage.Data.Entities.ChunkEntity", b =>
                {
                    b.Navigation("ChunkVector");
                });

            modelBuilder.Entity("Connapse.Storage.Data.Entities.ConnectionEntity", b =>
                {
                    b.Navigation("Sources");
                });

            modelBuilder.Entity("Connapse.Storage.Data.Entities.ContainerEntity", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Folders");
                });

            modelBuilder.Entity("Connapse.Storage.Data.Entities.DocumentEntity", b =>
                {
                    b.Navigation("BatchDocuments");

                    b.Navigation("ChunkVectors");

                    b.Navigation("Chunks");
                });

            modelBuilder.Entity("Connapse.Storage.Data.Entities.SourceEntity", b =>
                {
                    b.Navigation("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
